storage: .cache/verdaccio/storage
auth:
  htpasswd:
    file: .cache/verdaccio/htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@openai/codex-sdk':
    access: $all
    publish: $all
    proxy: npmjs
  '@openai/*':
    access: $all
    publish: $all
  '**':
    proxy: npmjs
log: { type: stdout, format: pretty, level: http }
